eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:4001/eureka/

spring:
  application:
    name: nephelo-consumer

server:
  port: 4003

security:
  oauth2:
    client:
      client-id: nephelo-client
      client-secret: nephelo-secret
      scope: read,write
      auto-approve-scopes: '.*'
      grant-type: password
  user:
    name: admin
    password: admin
    role: USER
  basic:
    enabled: false


swagger:
  basepackage: com.nephelo.consumer.controller
  service:
    name: nephelo-consumer
    description: nephelo-consumer后端服务接口
    developer: F1

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

zuul:
  routes:
    fcat-user:
      path: /nephelo-user/**
      serviceId: nephelo-user
  sensitive-headers:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true