spring:
    application:
        name: nephelo-center

server:
    port: 4001

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://localhost:${server.port}/eureka/
