#spring:
#  profiles:
#    active: dev

server:
  port: 8968

eureka:
  client:
      serviceUrl:
          defaultZone: http://localhost:8962/eureka/

spring:
  application:
      name: nephelo-user

jdbc:
  driver: jdbc:mysql://localhost:3306/fcat?useUnicode=true&characterEncoding=UTF8
  url:
  username:
  password: