spring:
    application:
        name: nephelo-user
    datasource:
        name: nephelo-user-dataSource
        url: jdbc:mysql://localhost/nephelo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: yanlin@123
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        logSlowSql: true
      #durid登陆账号密码
        loginUsername: admin
        loginPassword: admin
    redis:
        host:  localhost
        password: 123456
        database: 6
        timeout: 1800
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 0
          max-wait: -1

server:
    port: 4002

security:
    oauth2:
      client:
        client-id: nephelo-client
        client-secret: nephelo-secret
        scope: read,write
        auto-approve-scopes: '.*'
        grant-type: password
    user:
        name: admin
        password: admin
        role: USER
    basic:
      enabled: false

mybatis:
    basepackage: com.nephelo.user.mapper
    xmlLocation: classpath:mapper/**/*.xml

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:4001/eureka/

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000

ribbon:
  eureka:
    enabled: true

logging:
    level:
        tk.mybatis: DEBUG
        com.nephelo.user: DEBUG
    config: classpath:logback.xml
    path: /nephelo/user

swagger:
    basepackage: com.nephelo.user.controller
    service:
        name: nephelo-user
        description: nephelo-user后端服务接口
        developer: F1