#spring:
#  profiles:
#    active: dev

server:
  port: 8968

eureka:
  client:
      serviceUrl:
          defaultZone: http://localhost:8962/eureka/

spring:
  application:
    name: nephelo-user
  datasource:
    name: nephelo-datasource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nephelo?useUnicode=true&characterEncoding=UTF8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: yanlin@123
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


